<?xml version="1.0" encoding="utf-8"?><Database Name="CaFe" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\CaFe.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CaFeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Mag" Member="Mag">
    <Type Name="Mag">
      <Column Name="IdMag" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MagPerso" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LibelleMag" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sucre" Member="Sucre">
    <Type Name="Sucre">
      <Column Name="IdSucre" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QT_Sucre" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TypeConso" Member="TypeConso">
    <Type Name="TypeConso">
      <Column Name="IdTypeConso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LibelleConso" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>